package com.mohana.hotelanalytics.dto.response;

import com.mohana.hotelanalytics.entity.RoomType;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Revenue and booking volume breakdown by room type category")
public class RoomTypeRevenueResponse {

    @Schema(description = "Room accommodation category", example = "DELUXE")
    private RoomType roomType;

    @Schema(description = "Total revenue generated by this room type", example = "14500.00")
    private BigDecimal totalRevenue;

    @Schema(description = "Number of non-cancelled bookings in this room type", example = "12")
    private Long bookingCount;

    @Schema(description = "Average revenue yield per booking for this room type", example = "1208.33")
    private BigDecimal averageRevenue;

    @Schema(description = "Percentage share of total gross revenue", example = "28.5")
    private Double revenuePercentage;
}
